In [1]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [2]:
a.shape # 1D array

(6,)

In [4]:
b = np.arange(12).reshape(2,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# basic Operation of Numpy

In [9]:
a = np.array ([10,10,10])
b = np.array ([5,5,5])

In [10]:
a+b # Arthametic Operations

array([15, 15, 15])

In [11]:
a-b

array([5, 5, 5])

In [12]:
a*b

array([50, 50, 50])

In [13]:
a/b

array([2., 2., 2.])

In [14]:
# Comparison Operators

In [15]:
a<25

array([ True,  True,  True])

In [16]:
a>25

array([False, False, False])

In [17]:
b<25

array([ True,  True,  True])

In [18]:
b>25

array([False, False, False])

In [19]:
a+b<45

array([ True,  True,  True])

In [20]:
a*b<10

array([False, False, False])

In [ ]:
# Modifying an Existing Array rather than Creating new one

In [24]:
a *=3 
a

array([240, 240, 240])

In [25]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [26]:
a *=3
a

array([30, 30, 30])

In [27]:
b +=a
b

array([35, 35, 35])

In [28]:
# unary Operations

In [29]:
ages = np.array([12,15,18,20,22,24,16])
ages

array([12, 15, 18, 20, 22, 24, 16])

In [30]:
ages.sum()

127

In [31]:
ages.min()

12

In [32]:
ages.max()

24

In [33]:
ages.total()

AttributeError: 'numpy.ndarray' object has no attribute 'total'

In [34]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
numbers.reshape

<function ndarray.reshape>

In [ ]:
# req: I want to find the individual rows & cols

In [36]:
numbers .sum(axis=1)

array([ 6, 22, 38])

In [37]:
numbers .sum(axis=0)

array([12, 15, 18, 21])